gypman-tech/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::get('/' , 'HomeController@selectfunction')->name('main');
Route::get('showname/{id}','IndexController@showname');
Route::get('/select', 'HomeController@select')->name('select');
Route::get('/home', 'HomeController@selectfunction')->name('home');
Route::get('/seshowmain', 'HomeController@seshowmain')->name('seshowmain');
Route::get('/sedetail_action', 'HomeController@sedetail_search')->name('sedetail.action');
Route::get('resetpass', 'HomeController@reset_password')->name('reset_password');

Route::get('/homese', 'HomeController@home_se')->name('home_se');
Route::get('/datatablese', 'HomeController@datatable_se')->name('datatable_se');
Route::get('/ajaxse', 'HomeController@ajax_se')->name('ajax_se');
Route::post('/addse', 'HomeController@addse')->name('addse');

Route::get('/homeso', 'HomeController@home_so')->name('home_so');
Route::get('/datatableso', 'HomeController@datatable_so')->name('datatable_so');
Route::get('/ajaxso', 'HomeController@ajax_so')->name('ajax_so');

Route::get('/viewitem', 'HomeController@viewitem')->name('viewitem');
Route::get('/viewitem', 'HomeController@viewitemact')->name('viewitemact');
Route::get('/view_item_so/{id}', 'HomeController@getitemso')->name('getitemso');
Route::get('/view_item_se/{id}', 'HomeController@getitemse')->name('getitemse');
Route::get('/resultitem', 'HomeController@resultitem');
Route::get('resultcheck', 'HomeController@resu');
Route::get('/testso/{so_oder_number}', 'HomeController@testso');
Route::get('/createso', 'HomeController@create_so')->name('createso');
Route::get('/createse', 'HomeController@create_se')->name('createse');
Route::get('/testwip', 'HomeController@wip_test');
Route::get('/scanfg', 'HomeController@fetch_fg')->name('scanfg');
Route::get('/decodeitem', 'HomeController@viewitemdecode')->name('decodeitem');
Route::post('/fetchitemcode', 'HomeController@itemdecode')->name('fetchitemcode');
Route::get('/selectline', 'HomeController@selectwipline')->name('selectwipline');
Route::delete('/deleteline1wip/{id}', 'HomeController@deletewipline1')->name('deletewipline1');
Route::delete('/deletecodefg/{id}', 'HomeController@deletefg')->name('deletecodefg');
Route::get('/gencode', 'BarcodeGenController@genwipline1a')->name('gencode');
Route::get('/printwipline1a/{id}', 'HomeController@printwipl1a')->name('printwipl1a');
Route::get('/bplusdb', 'HomeController@connectdbplus')->name('bplusdb');
Route::get('/order', 'HomeController@viewoderall')->name('viewoderall');
Route::get('/cutstocks/{DI_KEY}', 'HomeController@cutstocks')->name('cutstocks');
Route::get('/transfer', 'HomeController@transfer')->name('transfer');
Route::post('/transfer_input', 'HomeController@transfer_input')->name('transfer_input');
Route::delete('/transfer_delete/{id}', 'HomeController@transfer_delete')->name('transfer_delete');

Route::get('/usersetting', 'UserController@index')->name('usersetting');
Route::get('/adduser', 'UserController@adduser')->name('adduser');
Route::get('/adjustuser', 'UserController@adjustuser')->name('adjustuser');

Route::resource('create_so', 'CreateSoController');
Route::resource('scanwip','ScanbarcodeController');
Route::resource('tagfg', 'FgbarcodeController');
Route::resource('wipline1a', 'Wipline1Controller');
Route::resource('wipline2', 'Wipline2Controller');

gypman-tech/app/SOTABLE.php
<?php
namespace App;
use Illuminate\Database\Eloquent\Model;
class SOTABLE extends Model
{
    public $table = "DOCINFO";

/*    public function getItems()
    {
        return $this->belongsTo(Item::class);
    }*/
}

gypman-tech/resources/views/so/ajax_so.blade.php
@extends('layouts.app')

@section('styles')
    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.16/css/jquery.dataTables.css">
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Detail</div>

                    <div class="panel-body">
                        <table class="table" id="datatable">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Name</th>
                                    <th>Date</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('javascripts')
    <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.js"></script>
    <script>
        $(document).ready( function () {
            $('#datatable').DataTable({
                "processing": true,
                "serverSide": true,
                "ajax": "{{ route('api.so.index') }}",
                "columns": [
                    { "data": "id" },
                    { "data": "name" },
                    { "data": "created_at" }
                ]
            });
        });
    </script>
@endsection

gypman-tech/resources/views/so/database_so.blade.php
@extends('layouts.app')

@section('styles')
    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.16/css/jquery.dataTables.css">
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Detail</div>

                    <div class="panel-body">
                        <table class="table" id="datatable">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Name</th>
                                    <th>Date</th>
                                </tr>
                            </thead>
                            <tbody>
                            @foreach ($so as $so)
                                <tr>
                                    <td>{{ $so->id}}</td>
                                    <td>{{ $so->name }}</td>
                                    <td>{{ $so->created_at }}</td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('javascripts')
    <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.js"></script>
    <script>
        $(document).ready( function () {
            $('#datatable').DataTable();
        });
    </script>
@endsection

gypman-tech/resources/views/so/table_so.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Detail</div>

                    <div class="panel-body">
                        <table class="table">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Date</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($so as $so)
                                <tr>
                                    <td>{{ $so->id }}</td>
                                    <td>{{ $so->name }}</td>
                                    <td>{{ $so->created_at }}</td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection